### ISSUE TITLE
TransactionInvoiceService doesn't have the document itself in the model after build_from_hash :(

### ISSUE THREAD

**Issue by krugerman007** [pfpayments/ruby-sdk#1]
Good morning dear developers. We are using your library and we are very happy :) Thanks.

Unfortunately, I have found one bug there:

```
document = PostFinanceCheckout::TransactionInvoiceService.new.get_invoice_document(space_id, document_id)

=> #<PostFinanceCheckout::RenderedDocument:0x000055d77f11a3d0 @document_template_type=1459425196590, @mime_type="application/pdf", @title="Invoice 698">

document.data

=> nil
```

This method gives no data back. It happens because of this line: https://github.com/pfpayments/ruby-sdk/blob/master/lib/postfinancecheckout-ruby-sdk/models/rendered_document.rb#L48

It should be not `:'data' => :'Array<String>'` but `:'data' => :'String`. According to the documentation: https://checkout.postfinance.ch/de-ch/doc/api/web-service#_rendereddocument

If I change in Gem-code this swagger_types, it works fine.

Could you please check and fix it? Thank you!

**Comment by theodorspringwallee** [comment]
Dear [krugerman007](https://github.com/krugerman007)

According to our devs, this should be fixed now in the newest version.
